### ISSUE TITLE
Shopping site integration availability in Indonesia

### ISSUE THREAD

**Issue by nri-baqir-muhammad** [zone-ict/overview#3]

**Comment by nri-baqir-muhammad** [comment]
@itoshinji-san, for this after my research, the best way for CB (cross-border) ecommerce with ease is to use Shopee Cross Border https://www.shopee.jp. With it basically the products sold by the factory can show up directly in Shopee applications in South East Asian countries

**Comment by itoshinji** [comment]
@nriin-mbaqir can we try something for the hackathon?

**Comment by nri-baqir-muhammad** [comment]
@itoshinji-san, for Shopee CB I don't think we can get anything for them for the hackathon timeframe. However, we can setup a Shopify store for the e-commerce aspect of the business. There's also support for setting up the store for international purchasers, but the shipping method is still fulfilled manually by the store https://www.shopify.com/markets

**Comment by itoshinji** [comment]
ok understand @nriin-mbaqir
