### ISSUE TITLE
Web App Design

### ISSUE THREAD

**Issue by nri-baqir-muhammad** [zone-ict/overview#4]
- [ ] Auth
- [x] Booking
  - [x] Booking history
  - [x] Booking detail
  - [x] Cancel booking
  - [x] Review
- [x] Activity provider list
  - [x] Activity provider detail
  - [x] Activity detail
  - [x] Create booking

**Comment by nriin-simani** [comment]
Mockup: https://www.figma.com/file/KDmOUqbLkLfp7bny4MfRJy/Untitled?node-id=55%3A196
Prototype: https://www.figma.com/proto/KDmOUqbLkLfp7bny4MfRJy/Untitled?page-id=55%3A196&node-id=55%3A196&viewport=336%2C156%2C0.5&scaling=scale-down&starting-point-node-id=144%3A733

**Comment by nri-baqir-muhammad** [comment]
@itoshinji-san, please review the UI in Figma, as for now I've made the Booking History and Booking Details page UI. Currently working on the UI for the rest of the app.

**Comment by itoshinji** [comment]
@nriin-mbaqir looks good!
